spring.application.name=finance-tracker
spring.datasource.url=jdbc:h2:mem:financetracker
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true